Match User deploy
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    X11Forwarding no
    DisableForwarding yes
    PermitTTY no
    PermitTunnel no
